### ISSUE TITLE
Ability to set Default Refresh Rate

### ISSUE THREAD

**Issue by ponnex** [justasm/Bugstick#9]
from this library -> https://github.com/controlwear/virtual-joystick-android

It would be nice if Bugstick can also have the ability to change refresh rate

> By default the refresh rate to get the data is 20/sec (every 50ms). If you want more or less just set the listener with one more parameters to set the refresh rate in milliseconds.

joystick.setOnMoveListener(new JoystickView.OnMoveListener() { ... }, 17); // around 60/sec

**Comment by justasm** [comment]
I'm sorry, but I don't see the use case. Why would you want the callback to be triggered continuously? I understand that game loops work at a fixed update rate, but Bugstick and Android Views in general work according to a 'minimise unnecessary work' principle, hence the whole invalidation mechanism. Any app or game already has to handle nondeterministic input in the form of user touches, which do not happen on any schedule; input widgets like Bugstick can simply be treated as an extension of that.

If you want to _throttle_ the callbacks that you get out of Bugstick, there are multiple ways to accomplish this on top of the library, and Bugstick does not do anything to get in your way here. It does not make sense to complicate the library and its API if it is not appropriate for the majority of typical use cases.

**Comment by ponnex** [comment]
I'm sorry but I think I haven't explained myself but I am not using bugstick for any game development app but I am using it as an android controller to a robot that has a motor driver through bluetooth le. My problem is that when onDrag() is activated it send data(degrees, offset) continuously which maybe 10-100x per second in which it is beyond bluetooth le bit rate or transfer rate which I think is a problem. How can I intercept this in Android?

In my opinion though changing how many datas(degrees, offset) per second is appropriate for the majority of typical use cases be it a game or a controller :D

**Comment by justasm** [comment]
Thanks for the details. I have actually used Bugstick in a similar project so I can definitely say that you can make it work 😄

To return to the issue of whether this is the library's responsibility, it is practically only forwarding touch input events from the system. If there are ongoing touch events dispatched by Android (which are typically processed at 60Hz), then Bugstick will report the updates at 60Hz. If the user is not moving their finger and no touch events are happening, then Bugstick will not report any updates. I think this is the sensible and most obvious behaviour.

If you want updates that are _faster_ than 60Hz, you can run your own loop and interpolate the reported values as you wish. Since this may differ from app to app (some may want to reuse the last value, some may want to interpolate between the last two values with a single frame delay, etc) it does not make sense for Bugstick to be making that decision.

If you want / need updates that are _slower_ than 60Hz, as mentioned, you can throttle as needed and using a mechanism that is appropriate for your use case. Some examples:
1. When using the Bluetooth LE API in Android, you have to order your BLE commands in such a way that one completes before you execute the next one to ensure reliable transmission. The most obvious way to do this is to have some abstraction around the commands, and instead of executing them directly, stick them into a queue that gets processed at the rate that the hardware can manage. If you have such a mechanism, you can submit commands to the queue at any rate, be it 10Hz or 100Hz, and still transmit at the proper rate. (Assuming queue consumption balances out production in the long term. If not, you could look at coalescing commands according to their type, e.g. if only the latest motor driver speed is important to transmit, you can remove stale speed commands from the queue if they have not yet been transmitted when you have a new command to submit.)
2. If you have a separate Thread that runs at a fixed but slower rate, you could cache the latest values that Bugstick reports into some variable. The Thread can then run as usual and process the latest values at the time that it gets around to process them.
3. If you want to 'debounce' the output, i.e. only transmit a value once it has settled and the user has stopped moving their finger for some duration, you could use some scheduling mechanism such as Android's Looper, its MessageQueue and a Handler to coordinate it. For example, to debounce with a 500ms window on Android's main thread, you could do:

``` java
float degrees;
float offset;

Runnable transmitRunnable = new Runnable() {
    @Override
    public void run() {
        // transmit degrees, offset
    }
};

Handler handler = new Handler(Looper.getMainLooper());

@Override
public void onDrag(float degrees, float offset) {
    handler.removeCallbacks(transmitRunnable);
    handler.postDelayed(transmitRunnable, 500);
}
```
